### ISSUE TITLE
Report generation fails with multiple devices attached

### ISSUE THREAD

**Issue by commjoen** [stanfy/spoon-gradle-plugin#42] opened 2015-02-27 13:51 UTC
I have encountered the following situation while using com.android.tools.build:gradle:1.1.2 and spoon-gradle-plugin:0.14.1:

- When I run gradle spoon with one device connected, I get proper html-reporting (e.g. build/spoon/... )
- When I run gradle spoon with multiple devices connected, then I get the error that results.json cannot be found.

Is there something that can be done about this? (feel free to contact me in any way)

**Comment by mknudsen** [comment] 2015-03-13 09:55
I think I have the same issue. I have two emulators, running tests in each one works fine, running them on both fails.


I am using `compileSdkVersion 21`, `buildToolsVersion "22"` and am using a Android 4.4.4 and 5.0 Emulator.

This exception gets printed

	java.lang.NoClassDefFoundError: org/kxml2/io/KXmlSerializer
	      at com.android.ddmlib.testrunner.XmlTestRunListener.generateDocument(XmlTestRunListener.java:161)
	      at com.android.ddmlib.testrunner.XmlTestRunListener.testRunEnded(XmlTestRunListener.java:149)
	      at com.android.ddmlib.testrunner.InstrumentationResultParser.handleOutputDone(InstrumentationResultParser.java:624)
	      at com.android.ddmlib.testrunner.InstrumentationResultParser.done(InstrumentationResultParser.java:601)
	      at com.android.ddmlib.MultiLineReceiver.flush(MultiLineReceiver.java:108)
	      at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:504)
	      at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:390)
	      at com.android.ddmlib.Device.executeShellCommand(Device.java:575)
	      at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:263)
	      at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:248)
	      at com.squareup.spoon.SpoonDeviceRunner.run(SpoonDeviceRunner.java:201)
	      at com.squareup.spoon.SpoonDeviceRunner.main(SpoonDeviceRunner.java:311)
	Caused by: java.lang.ClassNotFoundException: org.kxml2.io.KXmlSerializer
	      at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	      at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	      at java.security.AccessController.doPrivileged(Native Method)
	      at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	      at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	      ... 12 more

**Comment by roman-mazur** [comment] 2015-03-19 06:10
The reported issue seems to be what is described in #36 
But I haven't met @mknudsen's stacktrace.

**Comment by roman-mazur** [comment] 2015-03-19 07:01
ok, I see the problem with `org/kxml2/io/KXmlSerializer`.

**Comment by roman-mazur** [comment] 2015-03-19 08:27
Fixed in 1.0.0.

**Closed by roman-mazur** 2015-03-19 08:27 UTC
